services:
  - type: web
    name: brain-auto-posting
    runtime: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: autoposting-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: autoposting-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: WORKER_REGISTRATION_SECRET
        generateValue: true
      - key: WORKER_JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false

  - type: redis
    name: autoposting-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  - name: autoposting-db
    databaseName: autoposting
    user: autoposting_user
    plan: starter